import express, { Application } from "express";
import cors from "cors";
import dotenv from "dotenv";
import { login, register } from "./controller/login/register";
import { getProfile } from "./controller/profile";
dotenv.config();
const app: Application = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cors());
app.post("/login", login);
app.post("/register", register);
app.get("/profile", getProfile);
export default app;
